languages:
   Ruby: false
   JavaScript: false
   Python: true
   PHP: false
exclude_paths:
- "build/*"
- "support/*"
- "WAIL.spec"
- "bundledApps/heritrix-3.4.0-20240909/*"
- "bundledApps/html/*"
- "bundledApps/tomcat/*"
