import PropTypes from 'prop-types'
import React, { Component } from 'react'
import { CardActions } from 'material-ui/Card'
import FlatButton from 'material-ui/FlatButton'
import { Form, FieldArray, reduxForm } from 'redux-form/immutable'
import CardHeader from 'material-ui/Card/CardHeader'
import pure from 'recompose/pure'
import SearchTermList from './SearchTermList'
