const moment = require('moment')
// require('moment-precise-range-plugin')
const EventEmitter = require('eventemitter3')
const DB = require('nedb')
const _ = require('lodash')
const util = require('util')
const Immutable = require('immutable')
const Promise = require('bluebird')
const S = require('string')
const cp = require('child_process')
const fs = require('fs-extra')
const through2 = require('through2')
const prettyBytes = require('pretty-bytes')
const path = require('path')
const schedule = require('node-schedule')
const Twit = require('twit')
const request = require('request')
const progress = require('request-progress')
const prettyMs = require('pretty-ms')
const prettySeconds = require('pretty-seconds')
const Rx = require('rxjs')
const delay = require('lodash/delay')
const findP = require('find-process')
// */5 * * * *
// const Twit = require('twit')
//
const inspect = _.partialRight(util.inspect, { depth: null, colors: true })

findP('name', 'java')
  .then(list => {
    console.log(inspect(list))
  })